### ISSUE TITLE
Queue up certificate creation jobs

### ISSUE THREAD

**Issue by pezholio** [theodi/certificate-factory#6]
Rather than running this on someone's machine somewhere and waiting God knows how long to create certificates, @pkqk has suggested we use some sort of queuing system (I guess probably Resque) to queue up certificate generation, so we can fire and forget. Once the job is complete, we can fire off an email to the administrator to let them know all is well.

This would also help us with https://github.com/theodi/open-data-certificate/issues/1140, which would mean we can requeue a dataset if there's a temporary issue.

We could probably run this on Heroku or something too.

**Comment by pkqk** [comment]
certificates already has delayedjob in it (this isn't particularly appropriate but we could move those jobs to resque or sidekiq).

A lot of the stuff that is in certificate-factory doesn't need to be a separate codebase. The models should expose a definite way to do all this and the api should just be an external interface to it so other systems can kick off the same tasks.

**Comment by pezholio** [comment]
This is very true. I'm sure there was some sort of logic in separating this out, but I can't actually remember what it was now!
